coursework_design_studio-master/CourseWork/CourseWork/Controllers/Users1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CourseWork.Models;

namespace CourseWork.Controllers
{
    [Authorize(Roles = "admin, user")]
    public class Users1Controller : Controller
    {
        private designStudioEntities db = new designStudioEntities();

        // GET: Users1
        
        public ActionResult Index(string searchString_login, string searchString_role)
        {
            var Users_ = from u in db.Users
                         select u;

            if (!String.IsNullOrEmpty(searchString_login) || !String.IsNullOrEmpty(searchString_role))
            {
                

                Users_ = Users_.Where(u => u.login.Contains(searchString_login) &&  u.role.Contains(searchString_role)
                                       );
            }

            return View(Users_.ToList());
        }

        // GET: Users1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,login,password,role")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,login,password,role")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

coursework_design_studio-master/CourseWork/CourseWork/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @if (User.IsInRole("projManager"))
                    {
                        @:<li>@Html.ActionLink("Clients", "Index", "Clients")</li>
                        @:<li>@Html.ActionLink("Orders", "Index", "Orders")</li>
                        @:<li>@Html.ActionLink("Service Lists", "Index", "serviceLists")</li>
                        @:<li>@Html.ActionLink("Staffs", "Index", "Staffs")</li>
                    }
                    @if (User.IsInRole("Employee"))
                    {
                        @:<li>@Html.ActionLink("Clients", "Index", "Clients")</li>
                        @:<li>@Html.ActionLink("Orders", "Index", "Orders")</li>
                        @:<li>@Html.ActionLink("Service Lists", "Index", "serviceLists")</li>
                    }
                    @if (User.IsInRole("admin"))
                    {
                        @:<li>@Html.ActionLink("Clients", "Index", "Clients")</li>
                        @:<li>@Html.ActionLink("Orders", "Index", "Orders")</li>
                        @:<li>@Html.ActionLink("Services", "Index", "Services")</li>
                        @:<li>@Html.ActionLink("Service Lists", "Index", "serviceLists")</li>
                        @:<li>@Html.ActionLink("Staffs", "Index", "Staffs")</li>
                        @:<li>@Html.ActionLink("Teams", "Index", "Teams")</li>
                        @:<li>@Html.ActionLink("Users", "Index", "Users1")</li>
                    }
                    @if (User.IsInRole("client"))
                    {
                        @:<li>@Html.ActionLink("Orders", "Index", "Orders")</li>
                    }
                </ul>
                @if (!User.Identity.IsAuthenticated)
                {
                    <div class="form-inline my-2 my-md-0">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                @Html.ActionLink("Login", "Login", "Users", new { area = "" }, new { @class = "nav-link" })
                            </li>
                            
                        </ul>
                    </div>
                }
                else
                {
                    <div class="form-inline my-2 my-md-0">
                        <span class="fa-stack fa-2x has-badge" id="globalCounter" data-count="5">
                            <i class="fa fa-circle  fa-inverse"></i>
                            <i style="" class="fa fa-shopping-cart red-cart"></i>
                        </span>

                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@User.Identity.Name</a>
                                @Html.ActionLink("Logout", "Logout", "Users", new { area = "" }, new { @class = "nav-link dropdown-toggle" })
                            </li>
                        </ul>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>