coursework_design_studio-master/CourseWork/CourseWork/Models/order.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        

        public order()
        {
            this.serviceLists = new HashSet<serviceList>();
        }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]

        public int id { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<int> idTeam { get; set; }
        public Nullable<int> priceTotal { get; set; }
        public Nullable<int> hoursTotal { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
    
        public virtual client client { get; set; }
        public virtual team team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serviceList> serviceLists { get; set; }

        
        
    }
}

coursework_design_studio-master/CourseWork/CourseWork/Controllers/ordersController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using ClosedXML.Excel;
using CourseWork.Attributes;
using CourseWork.Models;
using Newtonsoft.Json;
using System.Web.Script.Serialization;



namespace CourseWork.Controllers
{
    [MyAuthorize(Roles = "admin, projManager, Employee, client")]
    public class ordersController : Controller
    {
        private designStudioEntities db = new designStudioEntities();
        private User currentUser;

        private User GetCurrentUser()
        {
            IEnumerable<Claim> claims = ((ClaimsIdentity)User.Identity).Claims;
            var id = int.Parse(claims.FirstOrDefault(i => i.Type == ClaimTypes.NameIdentifier).Value);
            currentUser = db.Users.FirstOrDefault(u => u.id == id);
            return currentUser;
        }
        // GET: orders
        public ActionResult Index(string sortOrder,string date_1, string date_2, string SearchString_FIO, string SearchString_team, int? year=2018)
        {
            GetCurrentUser();

            var orders = new List<order>();
            orders = db.orders.Include(o => o.client).Include(o => o.team).ToList();
            if (User.IsInRole("projManager") || User.IsInRole("Employee"))
            {
                var teamId = db.staffs.Where(s => s.idUser == currentUser.id).ToList()[0].idTeam;
                orders = db.orders.Where(o => o.idTeam == teamId).ToList();//.Include(o => o.client).Include(o => o.team).ToList();
            }
            if (User.IsInRole("client"))
            {
                orders = db.orders.Where(o => o.client.idUser == currentUser.id).ToList();
            }
            ViewBag.data = db.OrdersPriceToHoursProcedure().ToList();
            ViewBag.data1 = db.ordersAmountPerYear(year).ToList();
            ViewBag.year = year;
            //

            ViewBag.PriceTotalSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.HoursTotalSortParm = sortOrder == "HoursTotal" ? "HoursTotal_desc" : "HoursTotal";
            ViewBag.DateStartSortParm = sortOrder == "DateStart" ? "DateStart_desc" : "DateStart";
            ViewBag.DateFinishSortParm = sortOrder == "DateFinish" ? "DateFinish_desc" : "DateFinish";
            ViewBag.ClientFioSortParm = sortOrder == "ClientFio" ? "ClientFio_desc" : "ClientFio";

           var orders_ = from o in db.orders
                          select o;

          

            switch (sortOrder)
            {
                case "name_desc":
                    orders_ = orders_.OrderByDescending(o => o.priceTotal);
                    break;
                case "ClientFio":
                    orders_ = orders_.OrderBy(o => o.client.fio);
                    break;
                case "ClientFio_desc":
                    orders_ = orders_.OrderByDescending(o => o.client.fio);
                    break;
                case "HoursTotal":
                    orders_ = orders_.OrderBy(o => o.hoursTotal);
                    break;
                case "HoursTotal_desc":
                    orders_ = orders_.OrderByDescending(o => o.hoursTotal);
                    break;
                case "DateStart":
                    orders_ = orders_.OrderBy(o => o.startDate);
                    break;
                case "DateStart_desc":
                    orders_ = orders_.OrderByDescending(o => o.startDate);
                    break;
                case "DateFinish":
                    orders_ = orders_.OrderBy(o => o.finishDate);
                    break;
                case "DateFinish_desc":
                    orders_ = orders_.OrderByDescending(o => o.finishDate);
                    break;
               

                default:
                    orders_ = orders_.OrderBy(o => o.priceTotal);
                    break;
            }

            if (!String.IsNullOrEmpty(date_1) || !String.IsNullOrEmpty(date_2) || !String.IsNullOrEmpty(SearchString_FIO) || !String.IsNullOrEmpty(SearchString_team))
            {



                orders_ = orders_.Where(u =>u.startDate.ToString().Contains(date_1) && u.finishDate.ToString().Contains(date_2) 
                                       && u.client.fio.Contains(SearchString_FIO) && u.team.name.Contains(SearchString_team)
                                       );
            }

            //ViewBag.data = JsonConvert.SerializeObject(orders_.ToList());
           // var jsonSerialiser = new JavaScriptSerializer();
          //  ViewBag.json = jsonSerialiser.SerializeObject(orders_.ToList());

            string preserveReferenacesObjects = JsonConvert.SerializeObject(orders_, Formatting.Indented, new JsonSerializerSettings
            {
                PreserveReferencesHandling = PreserveReferencesHandling.Objects
            });

            ViewBag.dataY = preserveReferenacesObjects;
            var list = orders_.ToList();
            return View(list);
        }

        // GET: orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            order order = db.orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: orders/Create

        [MyAuthorize(Roles = "admin, projManager")]
        public ActionResult Create()
        {
            GetCurrentUser();
            ViewBag.idClient = new SelectList(db.clients, "id", "fio");
            ViewBag.idTeam = new SelectList(db.teams, "id", "name");
            if (User.IsInRole("projManager"))
            {
                var teamId = db.staffs.Where(s => s.idUser == currentUser.id).ToList()[0].idTeam.Value;
                ViewBag.idTeam = new SelectList(db.teams.Where(t => t.id == teamId), "id", "name");
            }
                
            return View();
        }

        // POST: orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [MyAuthorize(Roles = "admin, projManager")]
        public ActionResult Create([Bind(Include = "id,idClient,idTeam,priceTotal,hoursTotal,startDate,finishDate")] order order)
        {
            if (ModelState.IsValid)
            {
                order.finishDate = DateTime.Now;
                db.orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idClient = new SelectList(db.clients, "id", "fio", order.idClient);
            ViewBag.idTeam = new SelectList(db.teams, "id", "name", order.idTeam);
            return View(order);
        }

        // GET: orders/Edit/5
        [MyAuthorize(Roles = "admin, projManager")]
        public ActionResult Edit(int? id)
        {
            GetCurrentUser();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            order order = db.orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.idClient = new SelectList(db.clients, "id", "fio", order.idClient);
            ViewBag.idTeam = new SelectList(db.teams, "id", "name", order.idTeam);
            if (User.IsInRole("projManager"))
            {
                var teamId = db.staffs.Where(s => s.idUser == currentUser.id).ToList()[0].idTeam.Value;
                ViewBag.idTeam = new SelectList(db.teams.Where(t => t.id == teamId), "id", "name");
            }
            return View(order);
        }

        // POST: orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [MyAuthorize(Roles = "admin, projManager")]
        public ActionResult Edit([Bind(Include = "id,idClient,idTeam,priceTotal,hoursTotal,startDate,finishDate")] order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idClient = new SelectList(db.clients, "id", "fio", order.idClient);
            ViewBag.idTeam = new SelectList(db.teams, "id", "name", order.idTeam);
            return View(order);
        }

        // GET: orders/Delete/5
        [MyAuthorize(Roles = "admin, projManager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            order order = db.orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: orders/Delete/5
        [MyAuthorize(Roles = "admin, projManager")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            order order = db.orders.Find(id);
            db.orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public FileResult Export(string data)
        {


            designStudioEntities db = new designStudioEntities();

            DataTable dt = new DataTable("Orders");

coursework_design_studio-master/CourseWork/CourseWork/Controllers/servicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CourseWork.Models;

namespace CourseWork.Controllers
{
    public class servicesController : Controller
    {
        private designStudioEntities db = new designStudioEntities();

        // GET: services
        public ActionResult Index(DateTime? from, DateTime? to, string sortOrder, string SearchString_name, string SearchString_cost_1, string SearchString_cost_2)
        {
            if (!from.HasValue || !to.HasValue)
            {
                from = new DateTime(2018, 10, 1);
                to = new DateTime(2018, 12, 31);
            }
            var res = db.MostOrderedServices(from, to).ToList();
            ViewBag.pieChartData = res;
            ViewBag.from = from.ToString().Substring(0, 10);
            ViewBag.to = to.ToString().Substring(0, 10);

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.pricePerHourSortParm = sortOrder == "pricePerHour" ? "pricePerHour_desc" : "pricePerHour";


            var services = from s in db.services
                           select s;
            switch (sortOrder)
            {
                case "name_desc":
                    services = services.OrderByDescending(s => s.name);
                    break;
                case "pricePerHour":
                    services = services.OrderBy(s => s.pricePerHour);
                    break;
                case "pricePerHour_desc":
                    services = services.OrderByDescending(s => s.pricePerHour);
                    break;


                default:
                    services = services.OrderBy(s => s.name);
                    break;
            }

            if (!String.IsNullOrEmpty(SearchString_name) || !String.IsNullOrEmpty(SearchString_cost_1) || !String.IsNullOrEmpty(SearchString_cost_2))
            {
                if (!String.IsNullOrEmpty(SearchString_cost_1) || !String.IsNullOrEmpty(SearchString_cost_2))
                {
                    int cost_1 = Convert.ToInt32(SearchString_cost_1);
                    int cost_2 = Convert.ToInt32(SearchString_cost_2);

                    services = services.Where(s => s.name.Contains(SearchString_name) && (s.pricePerHour >= cost_1 && s.pricePerHour <= cost_2)
                                      );
                }

                services = services.Where(s => s.name.Contains(SearchString_name)
                                       );
            }

            return View(services.ToList());

        }

        // GET: services/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            service service = db.services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // GET: services/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: services/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,pricePerHour,description")] service service)
        {
            if (ModelState.IsValid)
            {
                db.services.Add(service);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(service);
        }

        // GET: services/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            service service = db.services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // POST: services/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,pricePerHour,description")] service service)
        {
            if (ModelState.IsValid)
            {
                db.Entry(service).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(service);
        }

        // GET: services/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            service service = db.services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // POST: services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            service service = db.services.Find(id);
            db.services.Remove(service);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

coursework_design_studio-master/CourseWork/CourseWork/Views/Orders/Create.cshtml
@model CourseWork.Models.order

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idClient, "idClient", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idClient", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idClient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idTeam, "idTeam", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idTeam", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idTeam, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.startDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.startDate, new { htmlAttributes = new { @class = "form-control" } })*@
                @{
                    var date = (DateTime.Now).Date.ToString().Substring(0, 10);

                }
                <input name="startDate" id="startDate" class="form-control" type="date" value="@date" />
                @Html.ValidationMessageFor(model => model.startDate, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

coursework_design_studio-master/CourseWork/CourseWork/Views/Orders/Delete.cshtml
@model CourseWork.Models.order

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.priceTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.priceTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hoursTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hoursTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.startDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.startDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.finishDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.finishDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.client.fio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.client.fio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.team.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.team.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

coursework_design_studio-master/CourseWork/CourseWork/Views/Orders/Details.cshtml
@model CourseWork.Models.order

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.priceTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.priceTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hoursTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hoursTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.startDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.startDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.finishDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.finishDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.client.fio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.client.fio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.team.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.team.name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

coursework_design_studio-master/CourseWork/CourseWork/Views/Orders/Index.cshtml
@model IEnumerable<CourseWork.Models.order>
@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm())
{
    <p>
        Find by FIO: @Html.TextBox("SearchString_FIO")
        Find by team: @Html.TextBox("SearchString_team")

        Find by start date: <input type="date" name="date_1" />
        Find by finish date: <input type="date" name="date_2" />

        <input type="submit" value="Search" />

    </p>
}
@using (Html.BeginForm("Export", "orders"))
{
    <input type="hidden" name="data" id="data" value="@ViewBag.dataY"/>
    <input type="submit" value="Export" />
}

<table class="table">
    <tr>
        <th>
            id
        </th>
        <th>
            @Html.ActionLink("Общая стоимость", "Index", new { sortOrder = ViewBag.PriceTotalSortParm })
        </th>
        <th>
            @Html.ActionLink("Общая продолжительность", "Index", new { sortOrder = ViewBag.HoursTotalSortParm })
        </th>
        <th>
            @Html.ActionLink("Дата начала", "Index", new { sortOrder = ViewBag.DateStartSortParm })
        </th>
        <th>
            @Html.ActionLink("Дата окончания", "Index", new { sortOrder = ViewBag.DateFinishSortParm })
        </th>
        <th>
            @Html.ActionLink("ФИО клиента", "Index", new { sortOrder = ViewBag.ClientFioSortParm })
        </th>
        <th>
            Название команды
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
    <tr>
        <td>
            @item.id
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.priceTotal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.hoursTotal)
        </td>
        <td>
            @item.startDate.ToString().Substring(0,10)
        </td>
        <td>
            @item.finishDate.ToString().Substring(0, 10)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.client.fio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.team.name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.id }) |

            @Html.ActionLink("Details", "Index", "serviceLists", new { id = item.id }, null) |

            @Html.ActionLink("Delete", "Delete", new { id = item.id })
        </td>
    </tr>
    }
</table>

@using (Html.BeginForm("Index", "services", FormMethod.Get, new { action = "#search", @id = "search" }))
{
    var fromInit = (new DateTime(2018, 1, 1)).ToString().Substring(0, 10);
    var toInit = (new DateTime(2018, 12, 31)).ToString().Substring(0, 10);

    <div class="form-horizontal">
        <h4>Вкажіть період для розрахунку статистики</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-1">
                <label for="from">Year: </label>
            </div>
            <div class="col-md-3">
                <input type="number" name="year" id="year" value="@ViewBag.year" />
            </div>

            <div>
                <button type="submit" class="btn btn-primary">Пошук</button>
            </div>
        </div>
    </div>
}

<canvas id="myChart1" style="height: 300px"></canvas>

<canvas id="myChart" style="height: 300px"></canvas>


<script>
    let data = @Html.Raw(Json.Encode(ViewBag.data))
    let data11 = @Html.Raw(Json.Encode(ViewBag.data1))
    let monthes = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
    let data1 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]
    for (let i = 0; i < data11.length; i++) {
        data1[data11[i].month - 1] = data11[i].ordersAmount
    }
    console.log(data)

    let hours = data.map(item => item.hoursTotal)
    let price = data.map(item => item.priceTotal)
    let ddata = data.map(item => {
        return {
            x: item.hoursTotal,
            y: item.priceTotal
        }
    })

    function compareRandom(a, b) {
        return Math.random() - 0.5;
    }

    //ddata.sort(compareRandom);
    console.log(ddata)

    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
        type: 'line',
        fill: true,
        data: {
            labels: hours,
            datasets: [{
                backgroundColor: "#3e95cd",
                data: ddata
            }]
        },

        options: {
            legend: {
                display: false,
                labels: {

                    fontSize: 16
                }
            },
            title: {
                display: true,
                text: 'Соотношение длительности исполнения заказа и его цены',
                fontSize: 20
            },
            tooltips: {
                callbacks: {
                    label: function (tooltipItem, data) {

                        var label = data.datasets[tooltipItem.datasetIndex].label || '';

                        if (label) {
                            label += ': ';
                        }

                        label += Math.round(tooltipItem.yLabel * 100) / 100 ;
                        return label;
                    }
                }
            }
        }
    });

    var ctx = document.getElementById('myChart1').getContext('2d');
    var chart = new Chart(ctx, {
        type: 'bar',
        fill: true,
        data: {
            labels: monthes,
            datasets: [{
                backgroundColor: "#3e95cd",
                data: data1,
            }]
        },

        options: {
            legend: {
                display: false,
                labels: {

                    fontSize: 16
                }
            },
            title: {
                display: true,
                text: 'Количество заказов за год',
                fontSize: 20
            }
        }
    });
</script>